# Generated by Django 2.2.3 on 2019-07-25 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hall name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=450, verbose_name='Name customer')),
                ('date', models.DateField(auto_now=True, verbose_name='Order date')),
                ('number_table', models.IntegerField(verbose_name='Number table')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email customer')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number table')),
                ('seats_count', models.IntegerField(verbose_name='Number of seats')),
                ('shape', models.CharField(choices=[('s', 'square'), ('o', 'oval')], max_length=100, verbose_name='Hall name')),
                ('horizontal_coordinates', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Horizontal coordinates')),
                ('vertical_coordinates', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Vertical coordinates')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Width table')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Height table')),
                ('order_status', models.IntegerField(verbose_name='Order status')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hall')),
            ],
        ),
    ]
